package com.example.ads.Classes.Utils

object AppConstants {
    const val Local_DATA_NAME = "DataStore"
    const val ADMOB_APP_ID = "ADMOB_APP_ID"
    const val ADMOB_INTERSTITIAL_ADS_ID = "ADMOB_INTERSTITIAL_ADS_ID"
    const val ADMOB_BANNER_ADS_ID = "ADMOB_BANNER_ADS_ID"
    const val ADMOB_REWARD_ADS_ID = "ADMOB_REWARD_ADS_ID"
    const val ADMOB_REWARD_INTERSTITIAL_ADS_ID = "ADMOB_REWARD_INTERSTITIAL_ADS_ID"
    const val ADMOB_NATIVE_ADS_ID = "ADMOB_NATIVE_ADS_ID"
    const val ADMOB_APP_OPEN_ADS_ID = "ADMOB_APP_OPEN_ADS_ID"

    const val APPLOVIN_SDK_KEY = "APPLOVIN_SDK_KEY"
    const val APPLOVIN_BANNER_ADS_ID = "APPLOVIN_BANNER_ADS_ID"
    const val APPLOVIN_INTERSTITIAL_ADS_ID = "APPLOVIN_INTERSTITIAL_ADS_ID"
    const val APPLOVIN_REWARD_ADS_ID = "APPLOVIN_REWARD_ADS_ID"


    const val MAX_BANNER_ADS_ID = "MAX_BANNER_ADS_ID"
    const val MAX_INTERSTITIAL_ADS_ID = "MAX_INTERSTITIAL_ADS_ID"
    const val MAX_REWARD_ADS_ID = "MAX_REWARD_ADS_ID"
    const val MAX_Native_ADS_ID = "MAX_Native_ADS_ID"


    const val ADMOB_INTERSTITIAL_ADS_ID_DEFAULT = "ca-app-pub-3940256099942544/1033173712"
    const val ADMOB_BANNER_ADS_ID_DEFAULT = "ca-app-pub-3940256099942544/6300978111"
    const val ADMOB_REWARD_ADS_ID_DEFAULT = "ca-app-pub-3940256099942544/5224354917"
    const val ADMOB_REWARD_INTERSTITIAL_ADS_ID_DEFAULT = "ca-app-pub-3940256099942544/5354046379"
    const val ADMOB_NATIVE_ADS_ID_DEFAULT = "ca-app-pub-3940256099942544/2247696110"
    const val ADMOB_APP_OPEN_ADS_ID_DEFAULT = "ca-app-pub-3940256099942544/3419835294"



    const val APPLOVIN_BANNER_ADS_ID_DEFAULT = "YOUR_ZONE_ID"
    const val APPLOVIN_INTERSTITIAL_ADS_ID_DEFAULT = "YOUR_AD_UNIT_ID"
    const val APPLOVIN_REWARD_ADS_ID_DEFAULT = "YOUR_AD_UNIT_ID"
    const val MAX_BANNER_ADS_ID_DEFAULT = "YOUR_AD_UNIT_ID"


    const val MAX_INTERSTITIAL_ADS_ID_DEFAULT = "YOUR_AD_UNIT_ID"
    const val MAX_REWARD_ADS_ID_DEFAULT = "YOUR_AD_UNIT_ID"
    const val MAX_Native_ADS_ID_DEFAULT = "YOUR_AD_UNIT_ID"

    //YOUR_ZONE_ID
    const val DEFAULT_VALUE = ""

    // Strategies
    const val ADS_VISIBLE_KEY="ADS_VISIBLE"
    const val ADS_STRATEGY_KEY="ADS_STRATEGY_KEY"


    const val ADS_VISIBLE = 0
    const val ADMOB_ADS = 0
    const val APPLOVIN_ADS = 1
    const val ADS_STRATEGY = 0
    const val CHECK_INTERSTITIAL_ADS_IS_LOADED="ADS_LOADED"
    var INTERSTITIAL_ADS_OPEN=false
}